services:
  collabohub-server:
    image: 027136969532.dkr.ecr.ap-northeast-2.amazonaws.com/collabohub-server:latest
    env_file:
      - .env
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    ports: 
      - 3000:3000
    depends_on:
      mysql-db:
        condition: service_healthy
      redis-db:
        condition: service_healthy
    restart: always

  mysql-db:
    image: mysql
    env_file:
      - .mysql.env
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
    restart: always

  redis-db:
    image: redis
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - ./redis_data:/data
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
    restart: always
