name: Deploy To EC2

on:
  push:
    branches: 
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies 
        run: npm ci

      - name: Create .env file  
        run: |
          echo "${{ secrets.ENV }}" > .env
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t collabohub-server .

      - name: Tag Docker image
        run: docker tag collabohub-server ${{ steps.login-ecr.outputs.registry }}/collabohub-server:latest

      - name: Push Docker image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/collabohub-server:latest

      - name: Deploy to EC2 via SSH 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            export CI_CD_GHB_TOKEN=${{ secrets.CI_CD_GHB_TOKEN }}
            
            cd ~

            if [ ! -d collabohub ]; then
                git clone https://x-access-token:${CI_CD_GHB_TOKEN}@github.com/miso1105/CollaboHub.git collabohub
              fi

            cd collabohub
            echo "${{ secrets.ENV }}" > .env

            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > .mysql.env
            echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .mysql.env

            docker compose pull collabohub-server
            docker compose down
            docker compose up -d     